# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-AvSP1wgkcN4balATHN5FzbrAAQyDDH4
"""

numero = int ( input ('digite um numero para saber se é primo'))

resultado = 0
for contador in range (2,numero):
       if (numero % contador) == 0 :
         resultado =  resultado + 1  
       else:
         resultado = resultado + 0

if resultado == 0 and numero > 2:
       print (numero, 'é primo')
else: 
       print (numero, 'não é primo')